default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: uselesssas
  password: test12345
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_course_development

test:
  <<: *default
  database: rails_course_test

production:
  <<: *default
  database: rails_course_production
  username: rails_course
  password: <%= ENV["RAILS_COURSE_DATABASE_PASSWORD"] %>
